name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true
#2
jobs:
  deploy:
    if: github.ref == 'refs/heads/main' 
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          command_timeout: 200m
          script: /
            cd /srv/www/cpichotel.com
            git pull
            docker compose build --force --no-cache --compress
            docker compose up -d