# Generated by Django 3.2.8 on 2021-12-21 08:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0003_auto_20211112_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.CharField(blank=True, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('rooms', models.CharField(blank=True, editable=False, max_length=50)),
                ('initial_amount', models.PositiveSmallIntegerField(blank=True, editable=False)),
                ('check_in_date_time', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 23, 38, 260464), editable=False)),
                ('last_edited_on', models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 23, 38, 260464), editable=False)),
            ],
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 23, 38, 256464)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 23, 38, 256464)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 23, 38, 256464)),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_duration', models.DurationField(editable=False, null=True)),
                ('total_amount', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('pay_amount', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('check_out_date_time', models.DateTimeField(editable=False, null=True)),
                ('check_in', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelSystem.checkin')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotelSystem.reservation'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
