# Generated by Django 3.2.8 on 2021-12-21 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0005_auto_20211221_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 57, 25, 435775), editable=False),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='last_edited_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 57, 25, 435775), editable=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 57, 25, 432775)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 57, 25, 432775)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 57, 25, 432775)),
        ),
    ]
