# Generated by Django 3.2.8 on 2021-12-21 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0006_auto_20211221_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 13, 28, 905889)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='initial_amount',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='last_edited_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 13, 28, 905889)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='rooms',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 13, 28, 902889)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 13, 28, 902889)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 13, 28, 902889)),
        ),
    ]
