# Generated by Django 3.2.8 on 2021-12-21 10:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0007_auto_20211221_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 14, 51, 251977)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='last_edited_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 14, 51, 251977)),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='check_out_date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pay_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='stay_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='total_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 14, 51, 249977)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 14, 51, 249977)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 14, 51, 249977)),
        ),
    ]
