# Generated by Django 3.2.8 on 2021-12-21 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0008_auto_20211221_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 26, 17, 178031)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='last_edited_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 26, 17, 178031)),
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='rooms',
        ),
        migrations.AddField(
            model_name='checkin',
            name='rooms',
            field=models.ManyToManyField(to='hotelSystem.Room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 26, 17, 172026)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 26, 17, 172026)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 18, 26, 17, 172026)),
        ),
    ]
