# Generated by Django 3.2.8 on 2021-12-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0013_auto_20211221_1853'),
    ]

    operations = [
    ]
