# Generated by Django 3.2.8 on 2021-12-26 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0016_auto_20211225_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('NR', 'Not Reserved'), ('R', 'Reserved'), ('CI', 'Checked In'), ('CO', 'Checked Out')], default='Not Reserved', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='check_in_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 20, 8, 46, 355714)),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='last_edited_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 20, 8, 46, 355714)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_arrival_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 20, 8, 46, 349715)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='expected_departure_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 20, 8, 46, 349715)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 20, 8, 46, 349715)),
        ),
    ]
